kind: pipeline
type: docker
name: PR Checker

steps:    

  - name: Build Sql Project
    image: ashwiniw/msbuild:1709-webdeploy
    commands:
    - dotnet build
      
trigger:
  branch:
    - develop
