kind: pipeline
type: docker
name: PR

steps:    

  - name: clean
    image: mcr.microsoft.com/dotnet/sdk:latest
    commands:
     - dotnet clean SQLProject_Drone_CICD.sln
     
  - name: build
    image: mcr.microsoft.com/dotnet/core/sdk:latest
    commands:
     - dotnet build SQLProject_Drone_CICD.sln
      
trigger:
  branch:
    - develop
---
kind: pipeline
type: docker
name: Publish and Deploy

steps:
  - name: publish
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    commands:
      - apt-get update -y
      - apt-get upgrade -y
      - apt-get install zip unzip -y
      - dotnet publish --configuration SQLProject_Drone_CICD.sln --output /drone/src/web/
      - cd /drone/src/web
      - zip -r output_file.zip *
      - cp -r output_file.zip /drone/src