kind: pipeline
type: docker
name: PR

steps:    
  - name: Open SQL 
    image: mcr.microsoft.com/mssql-tools
    commands:
     #- sqlcmd -S rg-demo-db.database.windows.net -d testDB -U MyServicePrincipal -P na0S_WG3yWfW.Lz4lq8k2r6~3bqg2AANF- -G
     #- sqlcmd -S 127.0.0.1 -U sa -P MyPassword100 > select @@version > go
     - /opt/mssql-tools/bin/sqlcmd -S mydemodatabase.database.windows.net -U cjmanaguelod18 -P @@Win4me@@cj1995 
      
trigger:
  branch:
    - develop
