kind: pipeline
type: docker
name: PR Checker

steps:    

  - name: Build Sql Project
    image: 404htm/msbuild
    commands:
    - docker build -t guid-generator-assets .
      
trigger:
  branch:
    - develop
