kind: pipeline
type: docker
name: PR Checker

steps:    

  - name: Build Sql Project
    image: nosinovacao/dotnet-sonar
    commands:
    - dotnet build SQLProject_Drone_CICD\SQLProject_Drone_CICD.sqlproj
      
trigger:
  branch:
    - develop
