kind: pipeline
type: docker
name: PR Checker

steps:    

  - name: Build Sql Project
    image: garrigueta/buildtools2019:latest
    commands:
    - dotnet build
      
trigger:
  branch:
    - develop
