kind: pipeline
type: docker
name: PR Checker

steps:    

  - name: Build Sql Project
    image: sjawhar/msbuild-ssdt:latest
    commands:
    - dotnet build SQLProject_Drone_CICD.sln
      
trigger:
  branch:
    - develop
