kind: pipeline
type: docker
name: PR Checker

steps:    

  - name: Build Sql Project
    image: rollersoftware/msbuild-windowsservercore
    commands:
    - dotnet build
      
trigger:
  branch:
    - develop
