kind: pipeline
type: docker
name: PR Checker

steps:    

  - name: Build Sql Project
    image: mcr.microsoft.com/dotnet/framework/aspnet
    commands:
    - dotnet build
      
trigger:
  branch:
    - develop
