kind: pipeline
type: docker
name: PR

steps:    

  - name: clean
    image: mcr.microsoft.com/dotnet/sdk:latest
    commands:
     - dotnet clean SQLProject_Drone_CICD.sln
     
  - name: build
    image: mcr.microsoft.com/dotnet/sdk:latest
    commands:
     - dotnet build SQLProject_Drone_CICD.sln
      
trigger:
  branch:
    - develop
