kind: pipeline
type: docker
name: PR

steps:    

  - name: clean
    image: mcr.microsoft.com/dotnet/core/sdk:latest
    commands:
     - dotnet clean SQLProject_Drone_CICD\SQLProject_Drone_CICD.csproj
     
  - name: build
    image: mcr.microsoft.com/dotnet/core/sdk:latest
    commands:
     - dotnet build SQLProject_Drone_CICD\SQLProject_Drone_CICD.csproj
      
trigger:
  branch:
    - develop
