kind: pipeline
type: docker
name: PR

steps:    

  - name: clean
    image: mcr.microsoft.com/dotnet/sdk:latest
    commands:
     - dotnet clean SQLProject_Drone_CICD.sln
     
  - name: build
    image: mcr.microsoft.com/dotnet/core/sdk:latest
    commands:
     - dotnet build SQLProject_Drone_CICD.sln
      
trigger:
  branch:
    - develop
---
kind: pipeline
type: docker
name: Publish and Deploy

steps:
   - name: deploy
    image: mcr.microsoft.com/azure-cli
    environment:
      client_ID:
        from_secret: client_ID
      tenant_ID:
        from_secret: tenant_ID
    commands:
      - az login --service-principal -u client_ID --tenant $tenant
      ##- az webapp deployment source config-zip --src /drone/src/output_file.zip -n $app_web_name -g $app_web_rg

