kind: pipeline
type: docker
name: PR Checker

steps:    

  - name: Build Sql Project
    image: ecragroup/aws-aspnet-framework
    commands:
    - dotnet build
      
trigger:
  branch:
    - develop
