kind: pipeline
type: docker
name: PR

steps:
  - name:  Pull docker
    image: docker
    commands:
     - docker run --privileged --name some-docker -d \
      --network some-network --network-alias docker \
      -e DOCKER_TLS_CERTDIR=/certs \
      -v some-docker-certs-ca:/certs/ca \
      -v some-docker-certs-client:/certs/client \
      docker:dind 
     
  - name: Open MSSQL Server
    image: mcr.microsoft.com/mssql/server:2017-latest
    commands:
     - docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=na0S_WG3yWfW.Lz4lq8k2r6~3bqg2AANF-' -p 1433:1433 -d mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
     
trigger:
  branch:
    - develop
