kind: pipeline
type: docker
name: PR

steps:    

  - name: clean
    image: mcr.microsoft.com/dotnet/core/sdk:latest
    commands:
     - dotnet clean SQLProject_Drone_CICD\SQLProject_Drone_CICD.csproj
     - dotnet add package MSBuild.Sdk.SqlProj --version 1.3.0
     
  - name: build
    image: mcr.microsoft.com/dotnet/core/sdk:latest
    commands:
     - dotnet build SQLProject_Drone_CICD\SQLProject_Drone_CICD.csproj
  
  - name: Open SQL 
    image: mcr.microsoft.com/mssql-tools
    commands:
     - Sqlcmd -S rg-demo-db.database.windows.net -d testDB -U MyServicePrincipal -P na0S_WG3yWfW.Lz4lq8k2r6~3bqg2AANF- -G
      
trigger:
  branch:
    - develop
    
    
