kind: pipeline
type: docker
name: PR

steps:    
  - name: Open MSSQL Server
    image: mcr.microsoft.com/mssql/server:2017-latest
    commands:
     - -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=na0S_WG3yWfW.Lz4lq8k2r6~3bqg2AANF-' -p 1433:1433 -d mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
     
trigger:
  branch:
    - develop
