kind: pipeline
type: docker
name: PR Checker

steps:    

  - name: Build Sql Project
    image: rollersoftware/msbuild-windowsservercore:latest
    commands:
    - msbuild.exe
      
trigger:
  branch:
    - develop
