kind: pipeline
type: docker
name: PR Checker

steps:    

  - name: Build Sql Project
    image: lexondocker/msbuildtest-v4:latest
    commands:
    - dotnet build
      
trigger:
  branch:
    - develop
