kind: pipeline
type: docker
name: PR

steps:
     
  - name: Open MSSQL Server
    image: mcr.microsoft.com/mssql/server:2017-latest
    commands:
     - docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=12345" `
       -p 1433:1433 --name sql1 `
       -d `
       mcr.microsoft.com/mssql/server:2017-latest
     
trigger:
  branch:
    - develop
